<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Enseignant extends \App\Entity\Enseignant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'nom_enseignant', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'prenom_enseignant', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'Grade', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'numTel', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'lieu_travail', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'Cin', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'disponibles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'nom_enseignant', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'prenom_enseignant', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'Grade', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'numTel', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'lieu_travail', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'Cin', '' . "\0" . 'App\\Entity\\Enseignant' . "\0" . 'disponibles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Enseignant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEnseignant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEnseignant', []);

        return parent::getNomEnseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEnseignant(string $nom_enseignant): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEnseignant', [$nom_enseignant]);

        return parent::setNomEnseignant($nom_enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomEnseignant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomEnseignant', []);

        return parent::getPrenomEnseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomEnseignant(string $prenom_enseignant): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomEnseignant', [$prenom_enseignant]);

        return parent::setPrenomEnseignant($prenom_enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrade(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrade', []);

        return parent::getGrade();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrade(string $Grade): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrade', [$Grade]);

        return parent::setGrade($Grade);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumTel', []);

        return parent::getNumTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumTel(string $numTel): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumTel', [$numTel]);

        return parent::setNumTel($numTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuTravail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuTravail', []);

        return parent::getLieuTravail();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuTravail(string $lieu_travail): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuTravail', [$lieu_travail]);

        return parent::setLieuTravail($lieu_travail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin(string $Cin): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$Cin]);

        return parent::setCin($Cin);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibiles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibiles', []);

        return parent::getDisponibiles();
    }

    /**
     * {@inheritDoc}
     */
    public function addDisponibile(\App\Entity\Disponibile $disponibile): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDisponibile', [$disponibile]);

        return parent::addDisponibile($disponibile);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDisponibile(\App\Entity\Disponibile $disponibile): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDisponibile', [$disponibile]);

        return parent::removeDisponibile($disponibile);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibles', []);

        return parent::getDisponibles();
    }

    /**
     * {@inheritDoc}
     */
    public function addDisponible(\App\Entity\Disponibile $disponible): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDisponible', [$disponible]);

        return parent::addDisponible($disponible);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDisponible(\App\Entity\Disponibile $disponible): \App\Entity\Enseignant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDisponible', [$disponible]);

        return parent::removeDisponible($disponible);
    }

}
