<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matiere extends \App\Entity\Matiere implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'Nom_matiere', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTHC', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTD', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTP', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'coefMatiere', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'semestre', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTotal'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'Nom_matiere', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTHC', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTD', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTP', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'coefMatiere', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'semestre', '' . "\0" . 'App\\Entity\\Matiere' . "\0" . 'NhTotal'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matiere $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMatiere(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMatiere', []);

        return parent::getNomMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMatiere(string $Nom_matiere): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMatiere', [$Nom_matiere]);

        return parent::setNomMatiere($Nom_matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNhTHC(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNhTHC', []);

        return parent::getNhTHC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNhTHC(int $NhTHC): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNhTHC', [$NhTHC]);

        return parent::setNhTHC($NhTHC);
    }

    /**
     * {@inheritDoc}
     */
    public function getNhTD(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNhTD', []);

        return parent::getNhTD();
    }

    /**
     * {@inheritDoc}
     */
    public function setNhTD(int $NhTD): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNhTD', [$NhTD]);

        return parent::setNhTD($NhTD);
    }

    /**
     * {@inheritDoc}
     */
    public function getNhTP(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNhTP', []);

        return parent::getNhTP();
    }

    /**
     * {@inheritDoc}
     */
    public function setNhTP(int $NhTP): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNhTP', [$NhTP]);

        return parent::setNhTP($NhTP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefMatiere(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefMatiere', []);

        return parent::getCoefMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefMatiere(float $coefMatiere): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefMatiere', [$coefMatiere]);

        return parent::setCoefMatiere($coefMatiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(int $Niveau): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$Niveau]);

        return parent::setNiveau($Niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', []);

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre(int $semestre): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', [$semestre]);

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNhTotal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNhTotal', []);

        return parent::getNhTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNhTotal(int $NhTotal): \App\Entity\Matiere
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNhTotal', [$NhTotal]);

        return parent::setNhTotal($NhTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
