<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLPBS7M5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLPBS7M5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLPBS7M5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLPBS7M5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLPBS7M5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LPBS7M5',
    'container.build_id' => '89805bb8',
    'container.build_time' => 1590539769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLPBS7M5');
